# Generated by Django 6.0.5 on 2026-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
